
services:
  image-backend:
    # build:
    #   context: ..
    #   dockerfile: ./dockers/Dockerfile.imagebackend
    image: ecolemiracledemo/ecole_mo9_demo:1.8.0
    env_file:
      - ./.env
    volumes:
      - ${MOUNT_JSON_DIR}:${JSON_DIR}:rw,Z
      - ${MOUNT_IMAGE_DIR}:${IMAGE_DIR}:rw,Z
      - ${MOUNT_TENSOR_DIR}:${TENSOR_DIR}:rw,Z
      - ${MOUNT_INITIAL_DATA_DIR}:${INITIAL_DATA_DIR}:rw,Z
      - ${MOUNT_DEFAULT_SAM_CKPT_DIR}:${DEFAULT_SAM_CKPT_DIR}:rw,Z
      - ${MOUNT_HF_HOME}:${HF_HOME}:rw,Z
      - ${MOUNT_CACHE_DIR}:${CACHE_DIR}:rw,Z
    ports:
      - ${IMAGE_BACKEND_PORT}:8000
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ["6"]
              capabilities: [gpu]

    
  coordinator:
    # build:
    #   context: ..
    #   dockerfile: ./dockers/Dockerfile.parser
    image: ecolemiracledemo/parser:1.8.0
    env_file:
      - ./.env
    volumes:
      - ${MOUNT_HF_HOME}:${HF_HOME}:rw,Z
    ports:
      - ${COORDINATOR_PORT}:8000
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ["6"]
              capabilities: [gpu]

  image-frontend:
    # build:
    #   context: ..
    #   dockerfile: ./dockers/Dockerfile.ui
    image: ecolemiracledemo/ecole-ui:1.8.0
    env_file:
      - ./.env
    ports:
      - ${IMAGE_FRONTEND_PORT}:8000
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ["6"]
              capabilities: [gpu]

  video-backend:
    # build:
    #   context: ..
    #   dockerfile: ./dockers/Dockerfile.video
    image: ecolemiracledemo/video-backend:1.8.0
    env_file:
      - ./.env

    ports:
      - ${VIDEO_BACKEND_PORT}:8000
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ["6"]
              capabilities: [gpu]

  
  mongodb:
    image: mongodb/mongodb-community-server:latest
    restart: always
    env_file:
      - ./.env
    ports:
        - "${MONGO_PORT}:27017"
    volumes:
      - ${MOUNT_MONGODB_DATA_DIR}/db:/data/db
      - ${MOUNT_MONGODB_DATA_DIR}/log:/var/log/mongodb

  data-server:
    # build:
    #   context: ..
    #   dockerfile: ./dockers/Dockerfile.dataserver
    image: ecolemiracledemo/data-server:1.8.0
    env_file:
      - ./.env

    ports:
      - ${DATA_SERVER_PORT}:8000
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ["6"]
              capabilities: [gpu]

    