
services:
  image-backend:
    build:
      context: ..
      dockerfile: ./dockers/Dockerfile.imagebackend
    image: ecolemiracledemo/ecole_mo9_demo:1.0.1
    env_file:
      - ./.env
    volumes:
      - ${MOUNT_JSON_DIR}:${JSON_DIR}:rw,Z
      - ${MOUNT_IMAGE_DIR}:${IMAGE_DIR}:rw,Z
      - ${MOUNT_TENSOR_DIR}:${TENSOR_DIR}:rw,Z
      - ${MOUNT_INITIAL_DATA_DIR}:${INITIAL_DATA_DIR}:rw,Z
      - ${MOUNT_DEFAULT_SAM_CKPT_DIR}:${DEFAULT_SAM_CKPT_DIR}:rw,Z
      - ${MOUNT_HF_HOME}:${HF_HOME}:rw,Z
      - ${MOUNT_CACHE_DIR}:${CACHE_DIR}:rw,Z
    ports:
      - "16004:8000"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ["6"]
              capabilities: [gpu]